# -*- coding: utf-8 -*-
"""
/***************************************************************************
 rasterize_polygonize
                                 A QGIS plugin
 A plugin that can perform rasterize and polygonize operations with a single tool.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-08-08
        copyright            : (C) 2024 by halukhndstn
        email                : halukhndstn@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load rasterize_polygonize class from file rasterize_polygonize.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rasterize_polygonize import rasterize_polygonize
    return rasterize_polygonize(iface)
